### ISSUE TITLE
Feature Request: Atomic Exchange

### ISSUE THREAD

**Issue by RossBencina** [mintomic/mintomic#7]
For some lock-free algorithms it is desirable to have an atomic exchange primitive. In the Win32 API this is called InterlockedExchange. x86 has the XCHG instruction, which is always atomic. C++11 has std::atomic_exchange()

So I'm thinking of:

uint32_t mint_exchange_32_relaxed(mint_atomic32_t *object, uint32_t operand);
uint64_t mint_exchange_64_relaxed(mint_atomic64_t *object, uint64_t operand);
void *mint_exchange_ptr_relaxed(mint_atomicPtr_t *object, size_t operand);

Is there a technical reason for the absence of these operations?

How complete would a patch need to be for it to be accepted? (i.e. how many operating systems, architectures, would a patch need to support?).

**Comment by preshing** [comment]
These functions are absent simply because I have never encountered an actual need for the atomic exchange operation in practice. (I have seen other people use atomic exchange in their code, but in every case I've seen, a simple atomic store would have done the job instead.) It's the same reason why sequentially consistent atomics are absent from Mintomic. Every lock-free algorithm and concurrent data structure I've ever needed in practice (so far) can be implemented using the operations Mintomic already has.

If you have an example of some code which accomplishes something useful using the atomic exchange operation, and cannot be implemented any other way, I would be very interested to know! That would maximize the chances of adding the operation to Mintomic. Feel free to reopen the issue if you can provide such an example. Thanks!

**Comment by RossBencina** [comment]
Hi Jeff, love your work.

Here are two examples of where atomic exchange is needed. In both cases an atomic exchange operation allows for a single-step wait-free implementation where otherwise a CAS retry loop would be needed.

__1. Pop-all operation on IBM freelist LIFO__
https://github.com/RossBencina/QueueWorld/blob/master/include/QwMpmcPopAllLifoStack.h
See the pop_all() method at the bottom.
The atomic-exchange primitive is used to remove all items in the queue at once. Without exchange this cannot be done safely if multiple readers try to pop_all() concurrently.

__2. push operation on Dmitry Vyukov Intrusive MPSC node-based FIFO__
http://www.1024cores.net/home/lock-free-algorithms/queues/intrusive-mpsc-node-based-queue
See  mpscq_push() method.
The atomic-exchange is used to push an item to the head of of the queue.

Thanks.

**Comment by RossBencina** [comment]
@preshing I don't have permissions to re-open the issue, however on the basis of my preceding comment I request that you reconsider. Thanks!

**Comment by preshing** [comment]
Maybe I'm asking too much, but it would be cool to have a (useful) sample application based on either of those classes. But an atomic exchange is not a big deal, and it's there among the C++11 low-level atomics, so OK, you've convinced me!

I've added the functions on Windows along with new test cases. To enable the new tests, you have to configure CMake with:
````
$ mkdir build
$ cd build
$ cmake -DMINT_HAS_EXCHANGE=1 ..
````
I haven't added support for MacOS, iOS or Linux yet. Once that's done, I'll enable the tests by default. If you want to speed up the process, feel free to send pull requests. Cheers.

**Comment by preshing** [comment]
I've added support for GCC x86/64. Tested on Cygwin x86, Cygwin x64, Debian Linux x64 and 32/64-bit MacOS targets.

I'll reopen the issue as a reminder to finish the ARM implementations.

**Comment by preshing** [comment]
Hi Ross, Mintomic is nearing the end of its life. I've basically moved all the atomic C code to Turf: https://github.com/preshing/turf/tree/master/turf/c

The native ARM support is actually disabled in Turf at the moment (due to missing `exchange` and `compareExchangeWeak`). It current falls back to C++11 atomics on ARM. I'll re-enable it once those missing functions are complete.

**Comment by RossBencina** [comment]
Thanks Jeff, I'll take a look. I guess it's time to switch to C++11 atomics for most things...
